"""Add pricing_rules table

Revision ID: 1cd1c8080167
Revises: 2b5d98c2fbfc
Create Date: 2026-10-09 11:45:20.405708

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1cd1c8080167'
down_revision: str | Sequence[str] | None = '2b5d98c2fbfc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.Column('pricing_model', sa.Enum('FIXED', 'INSPECTION_QUOTE', 'PROJECT_QUOTE', name='pricingmodel', native_enum=False), nullable=False),
    sa.Column('base_amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('visit_fee_paise', sa.BigInteger(), nullable=False),
    sa.Column('distance_fee_per_km_paise', sa.BigInteger(), nullable=False),
    sa.Column('distance_fee_threshold_km', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('emergency_fee_paise', sa.BigInteger(), nullable=False),
    sa.Column('platform_fee_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('worker_commission_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('material_charges_allowed', sa.Boolean(), nullable=False),
    sa.Column('material_charges_max_paise', sa.BigInteger(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['service_zones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricing_rules')
    # ### end Alembic commands ###
