"""add_worker_fields_and_categories

Revision ID: 20f9e263409e
Revises: 7ab193b81bc3
Create Date: 2026-10-09 10:41:37.446010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f9e263409e'
down_revision: Union[str, Sequence[str], None] = '7ab193b81bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_categories',
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('worker_id', 'category_id')
    )
    op.add_column('worker_profiles', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('worker_profiles', sa.Column('profile_photo_url', sa.Text(), nullable=True))
    op.add_column('worker_profiles', sa.Column('is_available', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_profiles', 'is_available')
    op.drop_column('worker_profiles', 'profile_photo_url')
    op.drop_column('worker_profiles', 'bio')
    op.drop_table('worker_categories')
    # ### end Alembic commands ###
