"""Add reviewed_by and reviewed_at to kyc_documents

Revision ID: 2b5d98c2fbfc
Revises: 20f9e263409e
Create Date: 2026-10-09 11:26:12.455369

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2b5d98c2fbfc'
down_revision: str | Sequence[str] | None = '20f9e263409e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_documents', sa.Column('reviewed_by', sa.UUID(), nullable=True))
    op.add_column('kyc_documents', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'kyc_documents', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kyc_documents', type_='foreignkey')
    op.drop_column('kyc_documents', 'reviewed_at')
    op.drop_column('kyc_documents', 'reviewed_by')
    # ### end Alembic commands ###
