"""add_subscriptions_tables

Revision ID: 2ed24090d38e
Revises: 040e0ddf34e1
Create Date: 2026-10-09 13:12:29.494552

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2ed24090d38e'
down_revision: str | Sequence[str] | None = '040e0ddf34e1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('worker_subscriptions',
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_subscriptions_ends_at'), 'worker_subscriptions', ['ends_at'], unique=False)
    op.create_index(op.f('ix_worker_subscriptions_is_active'), 'worker_subscriptions', ['is_active'], unique=False)
    op.create_index(op.f('ix_worker_subscriptions_plan_id'), 'worker_subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_worker_subscriptions_worker_id'), 'worker_subscriptions', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_subscriptions_worker_id'), table_name='worker_subscriptions')
    op.drop_index(op.f('ix_worker_subscriptions_plan_id'), table_name='worker_subscriptions')
    op.drop_index(op.f('ix_worker_subscriptions_is_active'), table_name='worker_subscriptions')
    op.drop_index(op.f('ix_worker_subscriptions_ends_at'), table_name='worker_subscriptions')
    op.drop_table('worker_subscriptions')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
