"""Add bookings table

Revision ID: 3b3e6a6607ea
Revises: 1cd1c8080167
Create Date: 2026-10-09 11:51:35.778179

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3b3e6a6607ea'
down_revision: str | Sequence[str] | None = '1cd1c8080167'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('address_lat', sa.Float(), nullable=False),
    sa.Column('address_lng', sa.Float(), nullable=False),
    sa.Column('address_text', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('pricing_rule_id', sa.UUID(), nullable=True),
    sa.Column('estimated_amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('final_amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('material_charges_paise', sa.BigInteger(), nullable=False),
    sa.Column('platform_fee_paise', sa.BigInteger(), nullable=True),
    sa.Column('worker_payout_paise', sa.BigInteger(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EN_ROUTE', 'IN_PROGRESS', 'COMPLETED', 'PAID', 'CANCELLED_BY_CUSTOMER', 'CANCELLED_BY_WORKER', 'CANCELLED_BY_ADMIN', name='bookingstatus', native_enum=False, length=40), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('en_route_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pricing_rule_id'], ['pricing_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_category_id'), 'bookings', ['category_id'], unique=False)
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_worker_id'), 'bookings', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_worker_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_category_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
