"""add_indexes_to_timestamp_and_status

Revision ID: 4eaf0669d0a1
Revises: 2ed24090d38e
Create Date: 2026-10-09 15:31:25.306413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eaf0669d0a1'
down_revision: Union[str, Sequence[str], None] = '2ed24090d38e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_customer_profiles_created_at'), 'customer_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_service_categories_created_at'), 'service_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_service_zones_created_at'), 'service_zones', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscription_plans_created_at'), 'subscription_plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_worker_categories_created_at'), 'worker_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_worker_profiles_created_at'), 'worker_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_worker_profiles_is_available'), 'worker_profiles', ['is_available'], unique=False)
    op.create_index(op.f('ix_worker_profiles_status'), 'worker_profiles', ['status'], unique=False)
    op.create_index(op.f('ix_worker_service_areas_created_at'), 'worker_service_areas', ['created_at'], unique=False)
    op.create_index(op.f('ix_worker_subscriptions_created_at'), 'worker_subscriptions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_subscriptions_created_at'), table_name='worker_subscriptions')
    op.drop_index(op.f('ix_worker_service_areas_created_at'), table_name='worker_service_areas')
    op.drop_index(op.f('ix_worker_profiles_status'), table_name='worker_profiles')
    op.drop_index(op.f('ix_worker_profiles_is_available'), table_name='worker_profiles')
    op.drop_index(op.f('ix_worker_profiles_created_at'), table_name='worker_profiles')
    op.drop_index(op.f('ix_worker_categories_created_at'), table_name='worker_categories')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_subscription_plans_created_at'), table_name='subscription_plans')
    op.drop_index(op.f('ix_service_zones_created_at'), table_name='service_zones')
    op.drop_index(op.f('ix_service_categories_created_at'), table_name='service_categories')
    op.drop_index(op.f('ix_customer_profiles_created_at'), table_name='customer_profiles')
    # ### end Alembic commands ###
