"""worker_profiles

Revision ID: 68974f3f1018
Revises: 860215ccd970
Create Date: 2026-10-09 09:15:17.701593

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '68974f3f1018'
down_revision: str | Sequence[str] | None = '860215ccd970'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ONBOARDING', 'PENDING_KYC', 'ACTIVE', 'SUSPENDED', 'REJECTED', name='workerlifecyclestatus', native_enum=False, length=50), nullable=False),
    sa.Column('current_location_lat', sa.Float(), nullable=True),
    sa.Column('current_location_lng', sa.Float(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('kyc_documents',
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.Enum('ID_CARD', 'PASSPORT', 'DRIVING_LICENSE', 'ADDRESS_PROOF', name='kycdoctype', native_enum=False, length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='kycstatus', native_enum=False, length=50), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kyc_documents')
    op.drop_table('worker_profiles')
    # ### end Alembic commands ###
