"""service_categories

Revision ID: 7054fe400ebe
Revises: 68974f3f1018
Create Date: 2026-10-09 09:25:15.987617

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7054fe400ebe'
down_revision: str | Sequence[str] | None = '68974f3f1018'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('pricing_model', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('icon_url', sa.String(length=1000), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['service_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_categories_is_active'), 'service_categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_service_categories_parent_id'), 'service_categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_service_categories_slug'), 'service_categories', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_categories_slug'), table_name='service_categories')
    op.drop_index(op.f('ix_service_categories_parent_id'), table_name='service_categories')
    op.drop_index(op.f('ix_service_categories_is_active'), table_name='service_categories')
    op.drop_table('service_categories')
    # ### end Alembic commands ###
